### ISSUE TITLE
Application becomes unresponsive when trying to define hom-set of product category

### ISSUE THREAD

**Issue by timjb** [SReichelt/slate#86]
The application becomes unresponsive after clicking on the placeholder with yellow background color:

![image](https://user-images.githubusercontent.com/124073/103139721-602ac880-46df-11eb-983a-b318dadfe180.png)

**Comment by SReichelt** [comment]
Thanks. This turned out to be a particularly bad (but fortunately easy to fix) performance problem. If this continues to happen in other situations, I'll make some more changes to avoid freezing the GUI.

Note that category theory is particularly prone to the problems described in #43, #44, and #69. So at the moment I recommend using the VSCode extension so that text input can be used as a fallback option.
